# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from csrtle/bumpEcho.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class bumpEcho(genpy.Message):
  _md5sum = "4f39b12694464cc7a7e355caf0f0ec3c"
  _type = "csrtle/bumpEcho"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time t
int32 x1
int32 y1
int32 x2
int32 y2
bool resp

"""
  __slots__ = ['t','x1','y1','x2','y2','resp']
  _slot_types = ['time','int32','int32','int32','int32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       t,x1,y1,x2,y2,resp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(bumpEcho, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.t is None:
        self.t = genpy.Time()
      if self.x1 is None:
        self.x1 = 0
      if self.y1 is None:
        self.y1 = 0
      if self.x2 is None:
        self.x2 = 0
      if self.y2 is None:
        self.y2 = 0
      if self.resp is None:
        self.resp = False
    else:
      self.t = genpy.Time()
      self.x1 = 0
      self.y1 = 0
      self.x2 = 0
      self.y2 = 0
      self.resp = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I4iB().pack(_x.t.secs, _x.t.nsecs, _x.x1, _x.y1, _x.x2, _x.y2, _x.resp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.t is None:
        self.t = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 25
      (_x.t.secs, _x.t.nsecs, _x.x1, _x.y1, _x.x2, _x.y2, _x.resp,) = _get_struct_2I4iB().unpack(str[start:end])
      self.resp = bool(self.resp)
      self.t.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I4iB().pack(_x.t.secs, _x.t.nsecs, _x.x1, _x.y1, _x.x2, _x.y2, _x.resp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.t is None:
        self.t = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 25
      (_x.t.secs, _x.t.nsecs, _x.x1, _x.y1, _x.x2, _x.y2, _x.resp,) = _get_struct_2I4iB().unpack(str[start:end])
      self.resp = bool(self.resp)
      self.t.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I4iB = None
def _get_struct_2I4iB():
    global _struct_2I4iB
    if _struct_2I4iB is None:
        _struct_2I4iB = struct.Struct("<2I4iB")
    return _struct_2I4iB
