# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from csrtle/PoseOrntBundle.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class PoseOrntBundle(genpy.Message):
  _md5sum = "4bf56cff2846ddf0c7c3fbc294b28115"
  _type = "csrtle/PoseOrntBundle"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time t
int8 x
int8 y
int8 o
"""
  __slots__ = ['t','x','y','o']
  _slot_types = ['time','int8','int8','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       t,x,y,o

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PoseOrntBundle, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.t is None:
        self.t = genpy.Time()
      if self.x is None:
        self.x = 0
      if self.y is None:
        self.y = 0
      if self.o is None:
        self.o = 0
    else:
      self.t = genpy.Time()
      self.x = 0
      self.y = 0
      self.o = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I3b().pack(_x.t.secs, _x.t.nsecs, _x.x, _x.y, _x.o))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.t is None:
        self.t = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 11
      (_x.t.secs, _x.t.nsecs, _x.x, _x.y, _x.o,) = _get_struct_2I3b().unpack(str[start:end])
      self.t.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I3b().pack(_x.t.secs, _x.t.nsecs, _x.x, _x.y, _x.o))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.t is None:
        self.t = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 11
      (_x.t.secs, _x.t.nsecs, _x.x, _x.y, _x.o,) = _get_struct_2I3b().unpack(str[start:end])
      self.t.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I3b = None
def _get_struct_2I3b():
    global _struct_2I3b
    if _struct_2I3b is None:
        _struct_2I3b = struct.Struct("<2I3b")
    return _struct_2I3b
