// Generated by gencpp from file csrtle/aendEcho.msg
// DO NOT EDIT!


#ifndef CSRTLE_MESSAGE_AENDECHO_H
#define CSRTLE_MESSAGE_AENDECHO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace csrtle
{
template <class ContainerAllocator>
struct aendEcho_
{
  typedef aendEcho_<ContainerAllocator> Type;

  aendEcho_()
    : t()
    , x(0)
    , y(0)
    , resp(false)  {
    }
  aendEcho_(const ContainerAllocator& _alloc)
    : t()
    , x(0)
    , y(0)
    , resp(false)  {
  (void)_alloc;
    }



   typedef ros::Time _t_type;
  _t_type t;

   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef uint8_t _resp_type;
  _resp_type resp;





  typedef boost::shared_ptr< ::csrtle::aendEcho_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::csrtle::aendEcho_<ContainerAllocator> const> ConstPtr;

}; // struct aendEcho_

typedef ::csrtle::aendEcho_<std::allocator<void> > aendEcho;

typedef boost::shared_ptr< ::csrtle::aendEcho > aendEchoPtr;
typedef boost::shared_ptr< ::csrtle::aendEcho const> aendEchoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::csrtle::aendEcho_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::csrtle::aendEcho_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::csrtle::aendEcho_<ContainerAllocator1> & lhs, const ::csrtle::aendEcho_<ContainerAllocator2> & rhs)
{
  return lhs.t == rhs.t &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.resp == rhs.resp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::csrtle::aendEcho_<ContainerAllocator1> & lhs, const ::csrtle::aendEcho_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace csrtle

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::csrtle::aendEcho_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::csrtle::aendEcho_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::csrtle::aendEcho_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::csrtle::aendEcho_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::csrtle::aendEcho_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::csrtle::aendEcho_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::csrtle::aendEcho_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6caf0aa0b7507bce1ec993aba0f1642b";
  }

  static const char* value(const ::csrtle::aendEcho_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6caf0aa0b7507bceULL;
  static const uint64_t static_value2 = 0x1ec993aba0f1642bULL;
};

template<class ContainerAllocator>
struct DataType< ::csrtle::aendEcho_<ContainerAllocator> >
{
  static const char* value()
  {
    return "csrtle/aendEcho";
  }

  static const char* value(const ::csrtle::aendEcho_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::csrtle::aendEcho_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time t\n"
"int32 x\n"
"int32 y\n"
"bool resp\n"
"\n"
;
  }

  static const char* value(const ::csrtle::aendEcho_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::csrtle::aendEcho_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.t);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.resp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct aendEcho_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::csrtle::aendEcho_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::csrtle::aendEcho_<ContainerAllocator>& v)
  {
    s << indent << "t: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.t);
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "resp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.resp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CSRTLE_MESSAGE_AENDECHO_H
