// Generated by gencpp from file csrtle/Kill.msg
// DO NOT EDIT!


#ifndef CSRTLE_MESSAGE_KILL_H
#define CSRTLE_MESSAGE_KILL_H

#include <ros/service_traits.h>


#include <csrtle/KillRequest.h>
#include <csrtle/KillResponse.h>


namespace csrtle
{

struct Kill
{

typedef KillRequest Request;
typedef KillResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Kill
} // namespace csrtle


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::csrtle::Kill > {
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::csrtle::Kill&) { return value(); }
};

template<>
struct DataType< ::csrtle::Kill > {
  static const char* value()
  {
    return "csrtle/Kill";
  }

  static const char* value(const ::csrtle::Kill&) { return value(); }
};


// service_traits::MD5Sum< ::csrtle::KillRequest> should match
// service_traits::MD5Sum< ::csrtle::Kill >
template<>
struct MD5Sum< ::csrtle::KillRequest>
{
  static const char* value()
  {
    return MD5Sum< ::csrtle::Kill >::value();
  }
  static const char* value(const ::csrtle::KillRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::csrtle::KillRequest> should match
// service_traits::DataType< ::csrtle::Kill >
template<>
struct DataType< ::csrtle::KillRequest>
{
  static const char* value()
  {
    return DataType< ::csrtle::Kill >::value();
  }
  static const char* value(const ::csrtle::KillRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::csrtle::KillResponse> should match
// service_traits::MD5Sum< ::csrtle::Kill >
template<>
struct MD5Sum< ::csrtle::KillResponse>
{
  static const char* value()
  {
    return MD5Sum< ::csrtle::Kill >::value();
  }
  static const char* value(const ::csrtle::KillResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::csrtle::KillResponse> should match
// service_traits::DataType< ::csrtle::Kill >
template<>
struct DataType< ::csrtle::KillResponse>
{
  static const char* value()
  {
    return DataType< ::csrtle::Kill >::value();
  }
  static const char* value(const ::csrtle::KillResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CSRTLE_MESSAGE_KILL_H
