// Generated by gencpp from file csrtle/PoseOrntBundle.msg
// DO NOT EDIT!


#ifndef CSRTLE_MESSAGE_POSEORNTBUNDLE_H
#define CSRTLE_MESSAGE_POSEORNTBUNDLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace csrtle
{
template <class ContainerAllocator>
struct PoseOrntBundle_
{
  typedef PoseOrntBundle_<ContainerAllocator> Type;

  PoseOrntBundle_()
    : t()
    , x(0)
    , y(0)
    , o(0)  {
    }
  PoseOrntBundle_(const ContainerAllocator& _alloc)
    : t()
    , x(0)
    , y(0)
    , o(0)  {
  (void)_alloc;
    }



   typedef ros::Time _t_type;
  _t_type t;

   typedef int8_t _x_type;
  _x_type x;

   typedef int8_t _y_type;
  _y_type y;

   typedef int8_t _o_type;
  _o_type o;





  typedef boost::shared_ptr< ::csrtle::PoseOrntBundle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::csrtle::PoseOrntBundle_<ContainerAllocator> const> ConstPtr;

}; // struct PoseOrntBundle_

typedef ::csrtle::PoseOrntBundle_<std::allocator<void> > PoseOrntBundle;

typedef boost::shared_ptr< ::csrtle::PoseOrntBundle > PoseOrntBundlePtr;
typedef boost::shared_ptr< ::csrtle::PoseOrntBundle const> PoseOrntBundleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::csrtle::PoseOrntBundle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::csrtle::PoseOrntBundle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::csrtle::PoseOrntBundle_<ContainerAllocator1> & lhs, const ::csrtle::PoseOrntBundle_<ContainerAllocator2> & rhs)
{
  return lhs.t == rhs.t &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.o == rhs.o;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::csrtle::PoseOrntBundle_<ContainerAllocator1> & lhs, const ::csrtle::PoseOrntBundle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace csrtle

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::csrtle::PoseOrntBundle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::csrtle::PoseOrntBundle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::csrtle::PoseOrntBundle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::csrtle::PoseOrntBundle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::csrtle::PoseOrntBundle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::csrtle::PoseOrntBundle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::csrtle::PoseOrntBundle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4bf56cff2846ddf0c7c3fbc294b28115";
  }

  static const char* value(const ::csrtle::PoseOrntBundle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4bf56cff2846ddf0ULL;
  static const uint64_t static_value2 = 0xc7c3fbc294b28115ULL;
};

template<class ContainerAllocator>
struct DataType< ::csrtle::PoseOrntBundle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "csrtle/PoseOrntBundle";
  }

  static const char* value(const ::csrtle::PoseOrntBundle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::csrtle::PoseOrntBundle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time t\n"
"int8 x\n"
"int8 y\n"
"int8 o\n"
;
  }

  static const char* value(const ::csrtle::PoseOrntBundle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::csrtle::PoseOrntBundle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.t);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.o);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseOrntBundle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::csrtle::PoseOrntBundle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::csrtle::PoseOrntBundle_<ContainerAllocator>& v)
  {
    s << indent << "t: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.t);
    s << indent << "x: ";
    Printer<int8_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int8_t>::stream(s, indent + "  ", v.y);
    s << indent << "o: ";
    Printer<int8_t>::stream(s, indent + "  ", v.o);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CSRTLE_MESSAGE_POSEORNTBUNDLE_H
