// Generated by gencpp from file csrtle/RTIatendResponse.msg
// DO NOT EDIT!


#ifndef CSRTLE_MESSAGE_RTIATENDRESPONSE_H
#define CSRTLE_MESSAGE_RTIATENDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace csrtle
{
template <class ContainerAllocator>
struct RTIatendResponse_
{
  typedef RTIatendResponse_<ContainerAllocator> Type;

  RTIatendResponse_()
    : atend(false)  {
    }
  RTIatendResponse_(const ContainerAllocator& _alloc)
    : atend(false)  {
  (void)_alloc;
    }



   typedef uint8_t _atend_type;
  _atend_type atend;





  typedef boost::shared_ptr< ::csrtle::RTIatendResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::csrtle::RTIatendResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RTIatendResponse_

typedef ::csrtle::RTIatendResponse_<std::allocator<void> > RTIatendResponse;

typedef boost::shared_ptr< ::csrtle::RTIatendResponse > RTIatendResponsePtr;
typedef boost::shared_ptr< ::csrtle::RTIatendResponse const> RTIatendResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::csrtle::RTIatendResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::csrtle::RTIatendResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::csrtle::RTIatendResponse_<ContainerAllocator1> & lhs, const ::csrtle::RTIatendResponse_<ContainerAllocator2> & rhs)
{
  return lhs.atend == rhs.atend;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::csrtle::RTIatendResponse_<ContainerAllocator1> & lhs, const ::csrtle::RTIatendResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace csrtle

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::csrtle::RTIatendResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::csrtle::RTIatendResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::csrtle::RTIatendResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::csrtle::RTIatendResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::csrtle::RTIatendResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::csrtle::RTIatendResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::csrtle::RTIatendResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74eb9cd583cb224ce5e6427d11f6cad3";
  }

  static const char* value(const ::csrtle::RTIatendResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74eb9cd583cb224cULL;
  static const uint64_t static_value2 = 0xe5e6427d11f6cad3ULL;
};

template<class ContainerAllocator>
struct DataType< ::csrtle::RTIatendResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "csrtle/RTIatendResponse";
  }

  static const char* value(const ::csrtle::RTIatendResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::csrtle::RTIatendResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool atend\n"
"\n"
;
  }

  static const char* value(const ::csrtle::RTIatendResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::csrtle::RTIatendResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.atend);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RTIatendResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::csrtle::RTIatendResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::csrtle::RTIatendResponse_<ContainerAllocator>& v)
  {
    s << indent << "atend: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.atend);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CSRTLE_MESSAGE_RTIATENDRESPONSE_H
