// Generated by gencpp from file csrtle/RTIatend.msg
// DO NOT EDIT!


#ifndef CSRTLE_MESSAGE_RTIATEND_H
#define CSRTLE_MESSAGE_RTIATEND_H

#include <ros/service_traits.h>


#include <csrtle/RTIatendRequest.h>
#include <csrtle/RTIatendResponse.h>


namespace csrtle
{

struct RTIatend
{

typedef RTIatendRequest Request;
typedef RTIatendResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RTIatend
} // namespace csrtle


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::csrtle::RTIatend > {
  static const char* value()
  {
    return "601274b2c558d8c19960f10fd7863a32";
  }

  static const char* value(const ::csrtle::RTIatend&) { return value(); }
};

template<>
struct DataType< ::csrtle::RTIatend > {
  static const char* value()
  {
    return "csrtle/RTIatend";
  }

  static const char* value(const ::csrtle::RTIatend&) { return value(); }
};


// service_traits::MD5Sum< ::csrtle::RTIatendRequest> should match
// service_traits::MD5Sum< ::csrtle::RTIatend >
template<>
struct MD5Sum< ::csrtle::RTIatendRequest>
{
  static const char* value()
  {
    return MD5Sum< ::csrtle::RTIatend >::value();
  }
  static const char* value(const ::csrtle::RTIatendRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::csrtle::RTIatendRequest> should match
// service_traits::DataType< ::csrtle::RTIatend >
template<>
struct DataType< ::csrtle::RTIatendRequest>
{
  static const char* value()
  {
    return DataType< ::csrtle::RTIatend >::value();
  }
  static const char* value(const ::csrtle::RTIatendRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::csrtle::RTIatendResponse> should match
// service_traits::MD5Sum< ::csrtle::RTIatend >
template<>
struct MD5Sum< ::csrtle::RTIatendResponse>
{
  static const char* value()
  {
    return MD5Sum< ::csrtle::RTIatend >::value();
  }
  static const char* value(const ::csrtle::RTIatendResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::csrtle::RTIatendResponse> should match
// service_traits::DataType< ::csrtle::RTIatend >
template<>
struct DataType< ::csrtle::RTIatendResponse>
{
  static const char* value()
  {
    return DataType< ::csrtle::RTIatend >::value();
  }
  static const char* value(const ::csrtle::RTIatendResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CSRTLE_MESSAGE_RTIATEND_H
