// Generated by gencpp from file csrtle/RTIbumpRequest.msg
// DO NOT EDIT!


#ifndef CSRTLE_MESSAGE_RTIBUMPREQUEST_H
#define CSRTLE_MESSAGE_RTIBUMPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace csrtle
{
template <class ContainerAllocator>
struct RTIbumpRequest_
{
  typedef RTIbumpRequest_<ContainerAllocator> Type;

  RTIbumpRequest_()
    : t()
    , x1(0)
    , y1(0)
    , x2(0)
    , y2(0)  {
    }
  RTIbumpRequest_(const ContainerAllocator& _alloc)
    : t()
    , x1(0)
    , y1(0)
    , x2(0)
    , y2(0)  {
  (void)_alloc;
    }



   typedef ros::Time _t_type;
  _t_type t;

   typedef int8_t _x1_type;
  _x1_type x1;

   typedef int8_t _y1_type;
  _y1_type y1;

   typedef int8_t _x2_type;
  _x2_type x2;

   typedef int8_t _y2_type;
  _y2_type y2;





  typedef boost::shared_ptr< ::csrtle::RTIbumpRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::csrtle::RTIbumpRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RTIbumpRequest_

typedef ::csrtle::RTIbumpRequest_<std::allocator<void> > RTIbumpRequest;

typedef boost::shared_ptr< ::csrtle::RTIbumpRequest > RTIbumpRequestPtr;
typedef boost::shared_ptr< ::csrtle::RTIbumpRequest const> RTIbumpRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::csrtle::RTIbumpRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::csrtle::RTIbumpRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::csrtle::RTIbumpRequest_<ContainerAllocator1> & lhs, const ::csrtle::RTIbumpRequest_<ContainerAllocator2> & rhs)
{
  return lhs.t == rhs.t &&
    lhs.x1 == rhs.x1 &&
    lhs.y1 == rhs.y1 &&
    lhs.x2 == rhs.x2 &&
    lhs.y2 == rhs.y2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::csrtle::RTIbumpRequest_<ContainerAllocator1> & lhs, const ::csrtle::RTIbumpRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace csrtle

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::csrtle::RTIbumpRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::csrtle::RTIbumpRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::csrtle::RTIbumpRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::csrtle::RTIbumpRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::csrtle::RTIbumpRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::csrtle::RTIbumpRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::csrtle::RTIbumpRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b776e1edb457fed3b060e7d733d94b13";
  }

  static const char* value(const ::csrtle::RTIbumpRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb776e1edb457fed3ULL;
  static const uint64_t static_value2 = 0xb060e7d733d94b13ULL;
};

template<class ContainerAllocator>
struct DataType< ::csrtle::RTIbumpRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "csrtle/RTIbumpRequest";
  }

  static const char* value(const ::csrtle::RTIbumpRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::csrtle::RTIbumpRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time t\n"
"int8 x1\n"
"int8 y1\n"
"int8 x2\n"
"int8 y2\n"
;
  }

  static const char* value(const ::csrtle::RTIbumpRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::csrtle::RTIbumpRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.t);
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.x2);
      stream.next(m.y2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RTIbumpRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::csrtle::RTIbumpRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::csrtle::RTIbumpRequest_<ContainerAllocator>& v)
  {
    s << indent << "t: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.t);
    s << indent << "x1: ";
    Printer<int8_t>::stream(s, indent + "  ", v.x1);
    s << indent << "y1: ";
    Printer<int8_t>::stream(s, indent + "  ", v.y1);
    s << indent << "x2: ";
    Printer<int8_t>::stream(s, indent + "  ", v.x2);
    s << indent << "y2: ";
    Printer<int8_t>::stream(s, indent + "  ", v.y2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CSRTLE_MESSAGE_RTIBUMPREQUEST_H
