// Generated by gencpp from file csrtle/RTIbump.msg
// DO NOT EDIT!


#ifndef CSRTLE_MESSAGE_RTIBUMP_H
#define CSRTLE_MESSAGE_RTIBUMP_H

#include <ros/service_traits.h>


#include <csrtle/RTIbumpRequest.h>
#include <csrtle/RTIbumpResponse.h>


namespace csrtle
{

struct RTIbump
{

typedef RTIbumpRequest Request;
typedef RTIbumpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RTIbump
} // namespace csrtle


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::csrtle::RTIbump > {
  static const char* value()
  {
    return "572d9da764261393a9c6c33976c42dac";
  }

  static const char* value(const ::csrtle::RTIbump&) { return value(); }
};

template<>
struct DataType< ::csrtle::RTIbump > {
  static const char* value()
  {
    return "csrtle/RTIbump";
  }

  static const char* value(const ::csrtle::RTIbump&) { return value(); }
};


// service_traits::MD5Sum< ::csrtle::RTIbumpRequest> should match
// service_traits::MD5Sum< ::csrtle::RTIbump >
template<>
struct MD5Sum< ::csrtle::RTIbumpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::csrtle::RTIbump >::value();
  }
  static const char* value(const ::csrtle::RTIbumpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::csrtle::RTIbumpRequest> should match
// service_traits::DataType< ::csrtle::RTIbump >
template<>
struct DataType< ::csrtle::RTIbumpRequest>
{
  static const char* value()
  {
    return DataType< ::csrtle::RTIbump >::value();
  }
  static const char* value(const ::csrtle::RTIbumpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::csrtle::RTIbumpResponse> should match
// service_traits::MD5Sum< ::csrtle::RTIbump >
template<>
struct MD5Sum< ::csrtle::RTIbumpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::csrtle::RTIbump >::value();
  }
  static const char* value(const ::csrtle::RTIbumpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::csrtle::RTIbumpResponse> should match
// service_traits::DataType< ::csrtle::RTIbump >
template<>
struct DataType< ::csrtle::RTIbumpResponse>
{
  static const char* value()
  {
    return DataType< ::csrtle::RTIbump >::value();
  }
  static const char* value(const ::csrtle::RTIbumpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CSRTLE_MESSAGE_RTIBUMP_H
