// Generated by gencpp from file csrtle/Spawn.msg
// DO NOT EDIT!


#ifndef CSRTLE_MESSAGE_SPAWN_H
#define CSRTLE_MESSAGE_SPAWN_H

#include <ros/service_traits.h>


#include <csrtle/SpawnRequest.h>
#include <csrtle/SpawnResponse.h>


namespace csrtle
{

struct Spawn
{

typedef SpawnRequest Request;
typedef SpawnResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Spawn
} // namespace csrtle


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::csrtle::Spawn > {
  static const char* value()
  {
    return "0b2d2e872a8e2887d5ed626f2bf2c561";
  }

  static const char* value(const ::csrtle::Spawn&) { return value(); }
};

template<>
struct DataType< ::csrtle::Spawn > {
  static const char* value()
  {
    return "csrtle/Spawn";
  }

  static const char* value(const ::csrtle::Spawn&) { return value(); }
};


// service_traits::MD5Sum< ::csrtle::SpawnRequest> should match
// service_traits::MD5Sum< ::csrtle::Spawn >
template<>
struct MD5Sum< ::csrtle::SpawnRequest>
{
  static const char* value()
  {
    return MD5Sum< ::csrtle::Spawn >::value();
  }
  static const char* value(const ::csrtle::SpawnRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::csrtle::SpawnRequest> should match
// service_traits::DataType< ::csrtle::Spawn >
template<>
struct DataType< ::csrtle::SpawnRequest>
{
  static const char* value()
  {
    return DataType< ::csrtle::Spawn >::value();
  }
  static const char* value(const ::csrtle::SpawnRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::csrtle::SpawnResponse> should match
// service_traits::MD5Sum< ::csrtle::Spawn >
template<>
struct MD5Sum< ::csrtle::SpawnResponse>
{
  static const char* value()
  {
    return MD5Sum< ::csrtle::Spawn >::value();
  }
  static const char* value(const ::csrtle::SpawnResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::csrtle::SpawnResponse> should match
// service_traits::DataType< ::csrtle::Spawn >
template<>
struct DataType< ::csrtle::SpawnResponse>
{
  static const char* value()
  {
    return DataType< ::csrtle::Spawn >::value();
  }
  static const char* value(const ::csrtle::SpawnResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CSRTLE_MESSAGE_SPAWN_H
