// Generated by gencpp from file csrtle/timeInt8.msg
// DO NOT EDIT!


#ifndef CSRTLE_MESSAGE_TIMEINT8_H
#define CSRTLE_MESSAGE_TIMEINT8_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace csrtle
{
template <class ContainerAllocator>
struct timeInt8_
{
  typedef timeInt8_<ContainerAllocator> Type;

  timeInt8_()
    : t()
    , data(0)  {
    }
  timeInt8_(const ContainerAllocator& _alloc)
    : t()
    , data(0)  {
  (void)_alloc;
    }



   typedef ros::Time _t_type;
  _t_type t;

   typedef int8_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::csrtle::timeInt8_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::csrtle::timeInt8_<ContainerAllocator> const> ConstPtr;

}; // struct timeInt8_

typedef ::csrtle::timeInt8_<std::allocator<void> > timeInt8;

typedef boost::shared_ptr< ::csrtle::timeInt8 > timeInt8Ptr;
typedef boost::shared_ptr< ::csrtle::timeInt8 const> timeInt8ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::csrtle::timeInt8_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::csrtle::timeInt8_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::csrtle::timeInt8_<ContainerAllocator1> & lhs, const ::csrtle::timeInt8_<ContainerAllocator2> & rhs)
{
  return lhs.t == rhs.t &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::csrtle::timeInt8_<ContainerAllocator1> & lhs, const ::csrtle::timeInt8_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace csrtle

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::csrtle::timeInt8_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::csrtle::timeInt8_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::csrtle::timeInt8_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::csrtle::timeInt8_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::csrtle::timeInt8_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::csrtle::timeInt8_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::csrtle::timeInt8_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ab6d0dd70600c3c29e7123d70261d97";
  }

  static const char* value(const ::csrtle::timeInt8_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ab6d0dd70600c3cULL;
  static const uint64_t static_value2 = 0x29e7123d70261d97ULL;
};

template<class ContainerAllocator>
struct DataType< ::csrtle::timeInt8_<ContainerAllocator> >
{
  static const char* value()
  {
    return "csrtle/timeInt8";
  }

  static const char* value(const ::csrtle::timeInt8_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::csrtle::timeInt8_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time t\n"
"int8 data\n"
;
  }

  static const char* value(const ::csrtle::timeInt8_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::csrtle::timeInt8_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.t);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct timeInt8_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::csrtle::timeInt8_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::csrtle::timeInt8_<ContainerAllocator>& v)
  {
    s << indent << "t: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.t);
    s << indent << "data: ";
    Printer<int8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CSRTLE_MESSAGE_TIMEINT8_H
